/**
 * Category knowledge used by the demo engine. Russian fields feed on-screen text and voiceover,
 * English fields feed image/video prompts (generators follow English instructions most reliably).
 */
export interface CategoryProfile {
  id: string;
  match: RegExp;
  audience: string;
  pain: string;
  painQuestion: string;
  desire: string;
  resultLine: string;
  objections: string[];
  env: string;
  timeOfDay: string;
  character: string;
  materials: string;
  palette: string;
  problemEn: string;
  problemRu: string;
  usageEn: string;
  usageRu: string;
  resultEn: string;
  resultRu: string;
  humorEn: string;
  humorRu: string;
  emotionEn: string;
  emotionRu: string;
  expertRu: string;
  hashtags: string[];
}

export const PROFILES: CategoryProfile[] = [
  {
    id: 'sleep',
    match: /храп|сон|сна|спальн|подушк|маска для сна|беруш/i,
    audience: 'Взрослые 30–55 лет, которые плохо высыпаются из-за храпа — своего или партнёра',
    pain: 'Храп мешает высыпаться и тому, кто храпит, и тому, кто спит рядом',
    painQuestion: 'Снова не выспались из-за храпа?',
    desire: 'Тихая ночь и бодрое утро без раздражения',
    resultLine: 'Утро, когда вы оба выспались',
    objections: ['Будет неудобно спать', 'Наверное, не поможет именно мне', 'Слишком дорого для эксперимента'],
    env: 'a cozy modern bedroom with linen bedding, a wooden nightstand and a dimmed bedside lamp',
    timeOfDay: 'late night',
    character: 'a woman in her mid-30s with shoulder-length dark brown hair, wearing a soft grey cotton pajama shirt, and her partner, a man in his late 30s with short hair and light stubble in a navy t-shirt',
    materials: 'crumpled white linen, matte wood, warm fabric textures',
    palette: 'deep navy, warm amber lamp light, soft beige',
    problemEn: 'the woman lies awake, pressing a pillow over her ear while her partner snores next to her',
    problemRu: 'Женщина не может уснуть — рядом громко храпит партнёр, она закрывает ухо подушкой',
    usageEn: 'the man calmly takes the product out of its package on the bedside table and prepares it for the night',
    usageRu: 'Мужчина достаёт товар из упаковки у прикроватной тумбы и готовится ко сну',
    resultEn: 'both partners sleep peacefully, the room is quiet, the clock shows 03:00',
    resultRu: 'Оба спокойно спят, в комнате тихо',
    humorEn: 'the woman wears giant construction ear-muffs in bed while the bedside lamp visibly vibrates from the snoring',
    humorRu: 'Жена спит в строительных наушниках, а ночник дрожит от храпа',
    emotionEn: 'the couple used to sleep in separate rooms; she looks at the empty half of the bed with sadness',
    emotionRu: 'Пара давно спит в разных комнатах — она с грустью смотрит на пустую половину кровати',
    expertRu: 'Храп возникает по разным причинам, поэтому решение должно быть удобным и подходить именно вам. При серьёзных проблемах со сном стоит обратиться к врачу',
    hashtags: ['#храп', '#сон', '#здоровыйсон', '#спальня', '#тихаяночь'],
  },
  {
    id: 'kitchen',
    match: /кухн|посуд|сковород|кастрюл|нож|блендер|чайник|контейнер для еды|терк/i,
    audience: 'Люди 25–50 лет, которые готовят дома и ценят время',
    pain: 'Готовка отнимает слишком много времени и сил после работы',
    painQuestion: 'Опять полчаса на то, что должно занимать пять минут?',
    desire: 'Быстро и без лишней посуды приготовить вкусный ужин',
    resultLine: 'Ужин готов, а кухня осталась чистой',
    objections: ['У меня уже есть похожее', 'Займёт место на кухне', 'Сложно мыть'],
    env: 'a bright modern kitchen with a light marble countertop, open shelves and a window with daylight',
    timeOfDay: 'early evening',
    character: 'a woman in her early 30s with a loose dark ponytail, wearing a mustard-yellow knit sweater with rolled-up sleeves',
    materials: 'polished marble, brushed steel, fresh vegetables with water droplets',
    palette: 'warm white, mustard yellow, fresh green',
    problemEn: 'she struggles with a pile of dirty dishes and a messy countertop, sighing at the clock',
    problemRu: 'Гора посуды, беспорядок на столе и взгляд на часы',
    usageEn: 'she uses the product on the countertop in one smooth confident motion',
    usageRu: 'Она пользуется товаром — одно уверенное движение',
    resultEn: 'she serves a finished plate on a clean countertop and smiles',
    resultRu: 'Готовое блюдо на чистом столе и довольная улыбка',
    humorEn: 'she fights a tomato with a spoon like a fencing duel while the cat watches judgmentally',
    humorRu: 'Она сражается с помидором ложкой, как на дуэли, кот наблюдает с осуждением',
    emotionEn: 'she cooks a dinner for her family who come home tired; warm reunion at the table',
    emotionRu: 'Она готовит ужин для семьи, которая вернулась уставшей',
    expertRu: 'Время на кухне чаще всего уходит на подготовку и мытьё. Удобный инструмент сокращает именно эти шаги',
    hashtags: ['#кухня', '#рецепты', '#лайфхакидлякухни', '#готовимдома', '#посуда'],
  },
  {
    id: 'beauty',
    match: /космет|крем|уход|волос|кож|сыворот|шампун|маск|макияж|ногт|парфюм/i,
    audience: 'Женщины 20–45 лет, которые следят за уходом и ищут понятные средства',
    pain: 'Сложно найти уход, который подходит и приятен в использовании',
    painQuestion: 'Полка средств, а результата, который нравится, всё нет?',
    desire: 'Ухоженный вид и простой ежедневный ритуал',
    resultLine: 'Ритуал ухода, который хочется повторять',
    objections: ['Не подойдёт моему типу', 'Очередная баночка', 'Неприятная текстура'],
    env: 'a minimalist bathroom with a round mirror, travertine shelf and soft towels',
    timeOfDay: 'morning',
    character: 'a woman in her late 20s with natural wavy chestnut hair tied in a claw clip, wearing a white waffle bathrobe',
    materials: 'travertine stone, frosted glass, creamy textures, water droplets',
    palette: 'warm sand, soft white, pale peach',
    problemEn: 'she looks at a crowded shelf of half-used products and frowns at her reflection',
    problemRu: 'Полка с недоиспользованными средствами и недовольный взгляд в зеркало',
    usageEn: 'she applies the product with her fingertips, showing the texture in close-up',
    usageRu: 'Она наносит средство кончиками пальцев, крупно видна текстура',
    resultEn: 'she smiles at her reflection in soft daylight, relaxed and confident',
    resultRu: 'Улыбка отражению в мягком утреннем свете',
    humorEn: 'she stands before a shelf with fifty bottles, a dramatic spotlight falls on just one product',
    humorRu: 'Пятьдесят баночек на полке — и драматичный луч света падает на одну',
    emotionEn: 'a quiet morning moment just for herself before a busy day',
    emotionRu: 'Тихие пять минут только для себя перед насыщенным днём',
    expertRu: 'Важен не объём средств, а регулярность и подходящий состав. Смотрите состав в карточке товара и делайте тест на чувствительность',
    hashtags: ['#уход', '#бьюти', '#уходзасобой', '#косметика', '#бьютинаходки'],
  },
  {
    id: 'auto',
    match: /авто|машин|автомоб|автокресл|видеорегистр|шин|салон/i,
    audience: 'Водители 25–55 лет, которые проводят в машине много времени',
    pain: 'В машине постоянно что-то мешает: беспорядок, неудобство, мелкие поломки',
    painQuestion: 'Знакомый хаос в салоне каждое утро?',
    desire: 'Порядок и комфорт в каждой поездке',
    resultLine: 'Спокойная поездка без мелких раздражителей',
    objections: ['Не подойдёт к моей машине', 'Будет мешать', 'Сложно установить'],
    env: 'the interior of a modern dark-grey hatchback parked on a city street',
    timeOfDay: 'morning golden hour',
    character: 'a man in his mid-30s with short dark hair, wearing a beige overshirt over a white t-shirt',
    materials: 'black leather, matte plastic dashboard, glass reflections',
    palette: 'graphite, warm sunrise orange, white',
    problemEn: 'items slide off the passenger seat as he brakes, he reaches for them in frustration',
    problemRu: 'Вещи разлетаются по салону при торможении, водитель раздражён',
    usageEn: 'he installs the product in the car in a few quick hand movements',
    usageRu: 'Он устанавливает товар в салоне за пару движений',
    resultEn: 'he drives relaxed with a tidy interior, sunlight through the windshield',
    resultRu: 'Спокойная поездка в аккуратном салоне',
    humorEn: 'a coffee cup performs a slow-motion flight across the cabin like in an action movie',
    humorRu: 'Стаканчик кофе летит через салон в замедленной съёмке, как в боевике',
    emotionEn: 'a father prepares the car for a weekend trip with his family',
    emotionRu: 'Отец готовит машину к поездке с семьёй на выходные',
    expertRu: 'Комфорт в машине складывается из мелочей. Проверьте совместимость с вашей моделью в характеристиках',
    hashtags: ['#авто', '#автотовары', '#водитель', '#автолайфхак', '#машина'],
  },
  {
    id: 'kids',
    match: /дет|малыш|ребен|ребён|игрушк|младен|школьн/i,
    audience: 'Родители детей 1–10 лет',
    pain: 'Родителям не хватает времени и сил на всё сразу',
    painQuestion: 'Как занять ребёнка хотя бы на 15 минут?',
    desire: 'Счастливый ребёнок и немного спокойствия для родителя',
    resultLine: 'Ребёнок увлечён, а у вас есть минутка на кофе',
    objections: ['Быстро надоест', 'Безопасно ли это', 'Займёт много места'],
    env: 'a bright Scandinavian-style kids room with a soft rug, low shelves and wooden toys',
    timeOfDay: 'afternoon',
    character: 'a mother in her early 30s with a blonde bun, wearing an oversized sage-green sweatshirt, and her 5-year-old son in a striped t-shirt',
    materials: 'soft wool rug, natural wood, cotton fabrics',
    palette: 'sage green, cream, soft wood tones',
    problemEn: 'the mother tries to work on a laptop while the child tugs at her sleeve',
    problemRu: 'Мама пытается работать, а ребёнок тянет её за рукав',
    usageEn: 'the child opens the product with excitement and starts using it on the rug',
    usageRu: 'Ребёнок с восторгом открывает товар и начинает играть',
    resultEn: 'the child is fully absorbed, the mother sips coffee and smiles',
    resultRu: 'Ребёнок увлечён, мама спокойно пьёт кофе',
    humorEn: 'the mother hides from the child behind the sofa holding a cup of coffee like a secret agent',
    humorRu: 'Мама прячется за диваном с кофе, как секретный агент',
    emotionEn: 'mother and child build something together and laugh',
    emotionRu: 'Мама и сын вместе что-то собирают и смеются',
    expertRu: 'Детям важно занятие по возрасту. Проверьте возрастную маркировку и сертификаты в карточке товара',
    hashtags: ['#дети', '#мамадетей', '#развитиедетей', '#игрушки', '#материнство'],
  },
  {
    id: 'sport',
    match: /спорт|фитнес|трениров|гантел|йог|коврик|бег|велосип/i,
    audience: 'Люди 20–45 лет, которые хотят тренироваться регулярно',
    pain: 'Сложно выдерживать регулярные тренировки',
    painQuestion: 'Снова отложили тренировку «на понедельник»?',
    desire: 'Тренироваться регулярно и с удовольствием',
    resultLine: 'Тренировка, которую не хочется пропускать',
    objections: ['Всё равно заброшу', 'Нет места дома', 'Нужен тренер'],
    env: 'a sunlit apartment living room cleared for a home workout, with a large window and plants',
    timeOfDay: 'morning',
    character: 'a woman in her late 20s with a high ponytail, wearing a charcoal sports top and olive leggings',
    materials: 'rubber textures, wooden floor, sweat sheen on skin',
    palette: 'olive, charcoal, bright daylight white',
    problemEn: 'she turns off the alarm and pulls the blanket back over her head',
    problemRu: 'Она выключает будильник и снова прячется под одеяло',
    usageEn: 'she trains with the product in a confident rhythmic movement',
    usageRu: 'Она тренируется с товаром в уверенном ритме',
    resultEn: 'she finishes the workout, breathing hard but smiling, sunlight on her face',
    resultRu: 'Тренировка завершена — тяжело дышит, но улыбается',
    humorEn: 'she negotiates with her couch, which seems to pull her back with invisible force',
    humorRu: 'Она «торгуется» с диваном, который будто тянет её обратно',
    emotionEn: 'she looks at an old photo and decides to start again today',
    emotionRu: 'Она смотрит на старое фото и решает начать снова — сегодня',
    expertRu: 'Регулярность важнее интенсивности. Удобный инвентарь дома снижает барьер для старта',
    hashtags: ['#фитнес', '#спортдома', '#тренировка', '#зож', '#мотивация'],
  },
  {
    id: 'electronics',
    match: /наушник|телефон|заряд|электрон|гаджет|кабел|колонк|смарт|часы|power ?bank|ноутбук/i,
    audience: 'Активные пользователи гаджетов 18–45 лет',
    pain: 'Гаджет подводит в самый неподходящий момент',
    painQuestion: 'Телефон сел ровно тогда, когда был нужнее всего?',
    desire: 'Техника, которая просто работает',
    resultLine: 'Всё под рукой и работает, когда нужно',
    objections: ['Есть дешевле', 'Сломается через месяц', 'Не совместимо с моим устройством'],
    env: 'a modern city café table by a large window with a laptop and a cup of flat white',
    timeOfDay: 'midday',
    character: 'a man in his late 20s with curly dark hair, wearing a black hoodie and silver wire-rim glasses',
    materials: 'anodized aluminum, matte plastic, glossy glass screens',
    palette: 'cool graphite, electric blue accents, warm café wood',
    problemEn: 'his phone screen goes black in the middle of an important call; he stares at it in disbelief',
    problemRu: 'Экран телефона гаснет посреди важного звонка',
    usageEn: 'he connects the product to his device with one click; a status light turns on',
    usageRu: 'Он подключает товар одним движением — загорается индикатор',
    resultEn: 'he continues working calmly, all devices active',
    resultRu: 'Спокойно продолжает работать — всё включено',
    humorEn: 'he runs through the café searching for a socket like in a spy chase',
    humorRu: 'Он ищет розетку по всему кафе, как в шпионской погоне',
    emotionEn: 'he manages to answer a video call from his mother at the right moment',
    emotionRu: 'Он успевает ответить на видеозвонок мамы в нужный момент',
    expertRu: 'Смотрите на ключевые характеристики и совместимость — они указаны в карточке товара',
    hashtags: ['#гаджеты', '#техника', '#электроника', '#полезныегаджеты', '#обзоргаджетов'],
  },
  {
    id: 'home',
    match: /уборк|дом|хранен|органайзер|швабр|пылесос|полотен|интерьер|ламп|текстил|ванн/i,
    audience: 'Люди 25–55 лет, которые хотят порядка дома без лишних усилий',
    pain: 'Порядок дома держится один день, а уборка съедает выходные',
    painQuestion: 'Убрались — а через день опять хаос?',
    desire: 'Чистый, уютный дом без марафона уборки',
    resultLine: 'Дом, в который приятно возвращаться',
    objections: ['Не впишется в интерьер', 'Очередная ненужная вещь', 'Сложно пользоваться'],
    env: 'a bright modern apartment with light oak floors, a beige sofa and plants on the windowsill',
    timeOfDay: 'Saturday morning',
    character: 'a woman in her late 30s with short auburn hair, wearing a denim shirt with rolled sleeves',
    materials: 'light oak, linen, ceramic, soft cotton',
    palette: 'oat beige, white, olive green',
    problemEn: 'she opens a cupboard and a pile of things falls out onto the floor',
    problemRu: 'Она открывает шкаф — и на пол вываливается гора вещей',
    usageEn: 'she uses the product and things fall into place in a satisfying motion',
    usageRu: 'Она использует товар — и всё встаёт на свои места',
    resultEn: 'she relaxes on the sofa with a cup of tea in a tidy, light-filled room',
    resultRu: 'Отдыхает на диване с чаем в чистой светлой комнате',
    humorEn: 'she opens the cupboard door wearing a helmet and holding a shield, prepared for an avalanche',
    humorRu: 'Она открывает шкаф в шлеме и со щитом, готовясь к лавине',
    emotionEn: 'she prepares her home to welcome guests and family for the holidays',
    emotionRu: 'Она готовит дом к приезду родных',
    expertRu: 'Порядок держится, когда у каждой вещи есть своё место и это удобно поддерживать',
    hashtags: ['#домашнийуют', '#порядоквдоме', '#уборка', '#хранение', '#длядома'],
  },
  {
    id: 'pets',
    match: /кош|собак|питом|корм|лежанк|когтеточ|поводок|аквариум/i,
    audience: 'Владельцы кошек и собак 20–50 лет',
    pain: 'Хочется, чтобы питомцу было хорошо, а дому — спокойно',
    painQuestion: 'Питомец опять устроил хаос, пока вас не было?',
    desire: 'Довольный питомец и порядок дома',
    resultLine: 'Питомец счастлив — и вы тоже',
    objections: ['Питомец не будет пользоваться', 'Быстро испортит', 'Займёт место'],
    env: 'a cozy living room with a soft rug, a grey sofa and afternoon sun through sheer curtains',
    timeOfDay: 'afternoon',
    character: 'a woman in her early 30s with straight black hair, wearing a cream knitted cardigan, and her ginger tabby cat',
    materials: 'soft fur, knitted wool, warm wood',
    palette: 'ginger orange, cream, warm grey',
    problemEn: 'she comes home to find torn paper and a guilty-looking cat on the sofa',
    problemRu: 'Хозяйка приходит домой — порванная бумага и виноватый кот на диване',
    usageEn: 'she places the product on the floor and the cat curiously approaches it',
    usageRu: 'Она ставит товар на пол, кот с любопытством подходит',
    resultEn: 'the cat happily uses the product while she watches smiling',
    resultRu: 'Кот с удовольствием пользуется товаром, хозяйка улыбается',
    humorEn: 'the cat sits like a boss on the sofa with a "manager" look while she cleans up',
    humorRu: 'Кот сидит как начальник, пока хозяйка убирает за ним',
    emotionEn: 'the cat greets her at the door after a long day and curls up next to her',
    emotionRu: 'Кот встречает её у двери после длинного дня',
    expertRu: 'Питомцам важны привычные запахи и удобство. Дайте время привыкнуть к новой вещи',
    hashtags: ['#кошки', '#собаки', '#питомцы', '#товарыдляживотных', '#котики'],
  },
];

export const GENERAL_PROFILE: CategoryProfile = {
  id: 'general',
  match: /.*/,
  audience: 'Покупатели Ozon 25–45 лет, которые ищут практичные решения для повседневной жизни',
  pain: 'Мелкая повседневная задача регулярно отнимает время и нервы',
  painQuestion: 'Знакомо, когда мелочь портит весь день?',
  desire: 'Простое решение, которое экономит время',
  resultLine: 'Задача решена — можно заняться важным',
  objections: ['Не уверен, что мне это нужно', 'Можно найти дешевле', 'Вдруг качество не то'],
  env: 'a bright modern apartment with neutral walls, a wooden table and soft daylight from a window',
  timeOfDay: 'daytime',
  character: 'a person in their early 30s with neat dark hair, wearing a light-blue casual shirt',
  materials: 'natural wood, soft fabric, matte ceramic',
  palette: 'neutral beige, white, accent of Ozon blue',
  problemEn: 'the person sighs in frustration while dealing with a small everyday inconvenience',
  problemRu: 'Человек раздражённо вздыхает над мелкой бытовой проблемой',
  usageEn: 'the person uses the product in one simple, confident motion',
  usageRu: 'Человек пользуется товаром — одно простое движение',
  resultEn: 'the person relaxes with a satisfied smile, the problem solved',
  resultRu: 'Проблема решена, довольная улыбка',
  humorEn: 'the person tries an absurdly complicated workaround with tape and three tools',
  humorRu: 'Человек пытается решить проблему скотчем и тремя инструментами сразу',
  emotionEn: 'the person finally has time for what they love after a busy week',
  emotionRu: 'После тяжёлой недели наконец есть время на любимое дело',
  expertRu: 'Хорошее решение — то, которым удобно пользоваться каждый день. Ключевые характеристики — в карточке товара',
  hashtags: ['#полезныевещи', '#товарыдлядома', '#находки', '#лайфхак', '#обзор'],
};

export function pickProfile(text: string): CategoryProfile {
  return PROFILES.find((p) => p.match.test(text)) ?? GENERAL_PROFILE;
}
