import type { ReelStyle } from './types';

// Knowledge base for the offline (Demo Mode) engine. Russian and English ideas are matched by word stems.
// JS `\b` does not work for Cyrillic, so stems are anchored with an explicit "not a letter" prefix.
const w = (...stems: string[]) => new RegExp(`(?:^|[^a-zа-яё])(?:${stems.join('|')})`, 'i');

export interface CharacterPreset {
  key: string;
  re: RegExp;
  label: string;
  ref: string;
  they: string;
  their: string;
  them: string;
  description: string;
  appearance: string;
  wardrobe: string;
  ru: string;
}

const she = { they: 'she', their: 'her', them: 'her' };
const he = { they: 'he', their: 'his', them: 'him' };
const it = { they: 'it', their: 'its', them: 'it' };

export const CHARACTERS: CharacterPreset[] = [
  { key: 'grandmother', re: w('бабушк', 'бабул', 'старушк', 'grandma', 'grandmother', 'old lady'), label: 'Grandmother (70s)', ref: 'the grandmother', ...she, description: 'a petite woman in her early 70s', appearance: 'silver hair in a neat low bun, round tortoiseshell glasses, laugh lines, warm brown eyes', wardrobe: 'a moss-green knitted cardigan over a cream blouse, a long navy pleated skirt, beige orthopedic loafers', ru: 'Бабушка' },
  { key: 'grandfather', re: w('дедушк', 'дед(?![а-яё])', 'старик', 'grandpa', 'grandfather', 'old man'), label: 'Grandfather (70s)', ref: 'the grandfather', ...he, description: 'a lean man in his mid-70s', appearance: 'short white hair, a trimmed white mustache, deep forehead wrinkles, bushy eyebrows', wardrobe: 'a brown tweed flat cap, a beige quilted vest over a checked flannel shirt, dark corduroy trousers', ru: 'Дедушка' },
  { key: 'girl', re: w('девочк', 'little girl'), label: 'Girl (8 years old)', ref: 'the girl', ...she, description: 'an 8-year-old girl', appearance: 'two messy chestnut braids, a gap-toothed grin, rosy cheeks, a small plaster on one knee', wardrobe: 'a yellow raincoat over a striped navy-and-white T-shirt, denim overalls, red rubber boots', ru: 'Девочка' },
  { key: 'boy', re: w('мальчик', 'ребён', 'ребен', 'little boy', 'kid(?![a-z])', 'child'), label: 'Boy (9 years old)', ref: 'the boy', ...he, description: 'a 9-year-old boy', appearance: 'tousled light-brown hair, freckles across the nose, a scraped elbow', wardrobe: 'an oversized red hoodie, cargo shorts, scuffed white sneakers, a small blue backpack', ru: 'Мальчик' },
  { key: 'young-woman', re: w('девушк', 'girl(?![a-z])', 'young woman', 'блогерш', 'студентк'), label: 'Young woman (mid-20s)', ref: 'the woman', ...she, description: 'a woman in her mid-20s', appearance: 'shoulder-length dark-brown hair with a loose wave, light freckles, natural makeup, small gold hoop earrings', wardrobe: 'an oversized cream cable-knit sweater, light-wash straight jeans, white leather sneakers', ru: 'Девушка' },
  { key: 'young-man', re: w('парен', 'парн', 'юнош', 'guy(?![a-z])', 'young man', 'студент(?!к)'), label: 'Young man (mid-20s)', ref: 'the man', ...he, description: 'a man in his mid-20s', appearance: 'short dark curly hair, light stubble, thick eyebrows, a thin silver chain', wardrobe: 'an olive bomber jacket over a plain white T-shirt, black slim chinos, grey running sneakers', ru: 'Парень' },
  { key: 'woman', re: w('женщин', 'мама', 'мать', 'woman', 'mom(?![a-z])', 'mother', 'lady'), label: 'Woman (40s)', ref: 'the woman', ...she, description: 'a woman in her early 40s', appearance: 'a chin-length auburn bob, faint crow\'s feet, minimal makeup, a thin gold watch', wardrobe: 'a camel wool coat over a black turtleneck, dark tailored trousers, black ankle boots', ru: 'Женщина' },
  { key: 'man', re: w('мужчин', 'папа', 'отец', 'man(?![a-z])', 'dad(?![a-z])', 'father'), label: 'Man (40s)', ref: 'the man', ...he, description: 'a man in his early 40s', appearance: 'short salt-and-pepper hair, a neatly trimmed beard, tired eyes behind black rectangular glasses', wardrobe: 'a navy quilted jacket over a light-blue oxford shirt, grey chinos, brown leather boots', ru: 'Мужчина' },
  { key: 'cat', re: w('кошк', 'котик', 'котён', 'котен', 'кот(?![а-яё])', 'кота(?![а-яё])', 'коту(?![а-яё])', 'cat(?![a-z])', 'kitten'), label: 'Ginger cat', ref: 'the cat', ...it, description: 'a chubby ginger tabby cat', appearance: 'bright amber eyes, a white chest patch, one slightly bent ear, long white whiskers', wardrobe: 'a thin red leather collar with a small brass bell', ru: 'Кот' },
  { key: 'dog', re: w('собак', 'пёс', 'пес(?![а-яё])', 'щен', 'dog(?![a-z])', 'pupp'), label: 'Golden retriever', ref: 'the dog', ...it, description: 'a young golden retriever', appearance: 'a fluffy honey-gold coat, a black nose, floppy ears, an always-wagging tail', wardrobe: 'a faded blue nylon collar with a round silver name tag', ru: 'Собака' },
  { key: 'courier', re: w('курьер', 'доставщик', 'courier', 'delivery'), label: 'Courier (late 20s)', ref: 'the courier', ...he, description: 'a delivery courier in his late 20s', appearance: 'short buzzed hair, a sweaty forehead, wireless earbuds in both ears', wardrobe: 'a bright yellow delivery jacket with reflective stripes, black cargo pants, a square insulated delivery backpack', ru: 'Курьер' },
  { key: 'chef', re: w('повар', 'шеф', 'chef', 'cook(?![a-z])'), label: 'Chef (30s)', ref: 'the chef', ...he, description: 'a chef in his mid-30s', appearance: 'a shaved head, a dark beard, forearm tattoos, a small burn mark on one hand', wardrobe: 'a white double-breasted chef jacket with rolled sleeves, a black apron, black non-slip clogs', ru: 'Повар' },
];

export const DEFAULT_CHARACTER: CharacterPreset = { key: 'person', re: /$^/, label: 'Woman (late 20s) — engine default', ref: 'the woman', ...she, description: 'a woman in her late 20s', appearance: 'a dark low ponytail, clear olive skin, minimal makeup', wardrobe: 'a charcoal hoodie, black leggings, white running sneakers', ru: 'Героиня' };

export interface LocationPreset {
  key: string;
  re: RegExp;
  label: string;
  short: string;
  environment: string;
  objects: string[];
  lighting: string;
  time: string;
  weather: string;
  palette: string;
  enter: string;
  routine: string;
  trigger: string;
  obstacle: string;
  goal: string;
  frame: string;
  artifactPlace: string;
  materials: string;
  textures: string;
  defaultWorld: string;
}

export const LOCATIONS: LocationPreset[] = [
  { key: 'car', re: w('машин', 'авто', 'такси', 'car(?![a-z])', 'taxi'), label: 'Car interior', short: 'the car', environment: 'the interior of a compact silver hatchback parked on the second level of a grey concrete parking garage', objects: ['steering wheel with a worn leather wrap', 'paper coffee cup in the cup holder', 'phone in a dashboard mount', 'rear-view mirror with a pine air freshener'], lighting: 'flat cool-white fluorescent garage light through the windshield, soft fill from the dashboard', time: 'early evening, after work', weather: 'dry and overcast outside the garage', palette: 'concrete grey, silver, muted navy, a pop of green from the air freshener', enter: 'slides into the driver\'s seat and drops {their} bag on the passenger seat', routine: 'adjusts the rear-view mirror and reaches for the ignition', trigger: 'pulls the driver\'s door shut with a heavy thunk', obstacle: 'the door handle clicks uselessly and the engine won\'t turn over', goal: 'drive home after a long day', frame: 'the windshield', artifactPlace: 'on the passenger seat', materials: 'worn black leather, matte dashboard plastic, scratched chrome trim', textures: 'fine dust on the dashboard, fingerprint smudges on the glass', defaultWorld: 'dinosaurs' },
  { key: 'elevator', re: w('лифт', 'elevator', 'lift(?![a-z])'), label: 'Elevator', short: 'the elevator', environment: 'a narrow office-building elevator with brushed-steel walls and a mirrored back panel', objects: ['illuminated floor-button panel', 'digital floor display', 'handrail', 'inspection certificate in a plastic frame'], lighting: 'cold overhead LED panel light with hard reflections in the steel', time: 'morning rush hour', weather: 'not visible — enclosed space', palette: 'brushed steel, cold white, black, amber floor numbers', enter: 'steps into the elevator and presses the button for the 14th floor', routine: 'checks {their} reflection and watches the floor numbers climb', trigger: 'watches the doors slide shut', obstacle: 'the buttons stop responding and the floor display shows symbols instead of numbers', goal: 'get to work on time', frame: 'the elevator doors', artifactPlace: 'on the elevator floor', materials: 'brushed stainless steel, mirror glass, rubber floor tiles', textures: 'faint scratches on the steel, smudged button panel', defaultWorld: 'space' },
  { key: 'kitchen', re: w('кухн', 'kitchen'), label: 'Home kitchen', short: 'the kitchen', environment: 'a small cozy apartment kitchen with white subway tiles, open wooden shelves and a window above the sink', objects: ['kettle on the stove', 'chipped ceramic mug', 'wooden cutting board with half a lemon', 'potted basil on the windowsill'], lighting: 'soft warm morning daylight from the window, gentle bounce off the white tiles', time: 'morning', weather: 'clear morning outside the window', palette: 'warm white, oak, sage green, lemon yellow', enter: 'walks into the kitchen in socks, yawning', routine: 'fills the kettle and switches it on', trigger: 'turns the tap on', obstacle: 'the tap won\'t turn off and the door to the hallway won\'t open', goal: 'make a quiet morning coffee', frame: 'the window above the sink', artifactPlace: 'next to the kettle', materials: 'glazed ceramic tiles, oiled oak, brushed steel', textures: 'water droplets on the tap, crumbs on the board, steam on the window', defaultWorld: 'underwater' },
  { key: 'office', re: w('офис', 'office', 'desk(?![a-z])'), label: 'Open-plan office', short: 'the office', environment: 'an open-plan office on a high floor with rows of white desks and floor-to-ceiling windows', objects: ['laptop with a spreadsheet open', 'mug of cold coffee', 'sticky notes on the monitor', 'a desk plant'], lighting: 'cool overcast daylight from the windows mixed with flat overhead fluorescents', time: 'late afternoon', weather: 'grey drizzle on the windows', palette: 'office white, grey carpet, cool blue window light, yellow sticky notes', enter: 'drops into {their} desk chair with a sigh', routine: 'stares at the spreadsheet and rubs {their} eyes', trigger: 'closes the laptop lid', obstacle: 'the office door won\'t open and every screen freezes on the same frame', goal: 'survive the last hour of the workday', frame: 'the floor-to-ceiling window', artifactPlace: 'on the keyboard', materials: 'laminate desks, mesh office chairs, glass', textures: 'carpet fibers, smudged glass, coffee ring stains', defaultWorld: 'medieval' },
  { key: 'subway', re: w('метро', 'вагон', 'электричк', 'subway', 'metro', 'train'), label: 'Subway car', short: 'the subway car', environment: 'a half-empty city subway car with plastic seats and a dark tunnel rushing past the windows', objects: ['steel grab poles', 'route map above the doors', 'a forgotten newspaper on a seat', 'flickering ad panel'], lighting: 'cold flickering fluorescent tubes, darkness outside', time: 'late evening', weather: 'not visible — underground', palette: 'cold fluorescent white, blue plastic seats, black tunnel, steel', enter: 'steps into the car and grabs a pole', routine: 'puts in earbuds and leans against the door', trigger: 'watches the doors close', obstacle: 'the doors won\'t open at the next station — there is no next station', goal: 'get home after a late shift', frame: 'the train window', artifactPlace: 'on the seat next to {them}', materials: 'molded plastic, brushed steel, scuffed rubber floor', textures: 'scratched windows, worn seat fabric, grime in the floor grooves', defaultWorld: 'underwater' },
  { key: 'street', re: w('улиц', 'город', 'тротуар', 'street', 'city', 'sidewalk'), label: 'City street', short: 'the street', environment: 'a narrow city street with parked cars, a bakery storefront and a crosswalk', objects: ['crosswalk signal', 'bicycle chained to a lamp post', 'bakery sign', 'puddle reflecting the sky'], lighting: 'low golden-hour sun raking down the street, long shadows', time: 'golden hour', weather: 'just after rain, wet asphalt', palette: 'warm amber, wet asphalt grey, brick red, teal shopfront', enter: 'walks down the sidewalk holding a coffee', routine: 'waits at the crosswalk, scrolling {their} phone', trigger: 'steps onto the crosswalk', obstacle: 'the crossing never ends — every step lands back at the curb', goal: 'cross the street to the bakery', frame: 'the street ahead', artifactPlace: 'on the sidewalk at {their} feet', materials: 'wet asphalt, brick, painted steel', textures: 'puddle reflections, cracked paint on the crosswalk, rain beads on cars', defaultWorld: 'future' },
  { key: 'cafe', re: w('кафе', 'кофейн', 'ресторан', 'cafe', 'café', 'coffee shop', 'restaurant'), label: 'Coffee shop', short: 'the coffee shop', environment: 'a small coffee shop with a marble counter, an espresso machine and a big street-facing window', objects: ['espresso machine', 'cappuccino with latte art', 'pastry display', 'chalkboard menu'], lighting: 'warm pendant lights plus soft daylight from the street window', time: 'mid-morning', weather: 'light snow falling outside the window', palette: 'espresso brown, cream, brass, soft white', enter: 'walks in from the cold, unwinding {their} scarf', routine: 'sits by the window with a cappuccino', trigger: 'takes the first sip', obstacle: 'the front door now opens onto a wall', goal: 'enjoy a quiet coffee break', frame: 'the café window', artifactPlace: 'next to the cup', materials: 'veined marble, brass, reclaimed wood', textures: 'milk foam, coffee grounds, condensation on the window', defaultWorld: 'winter' },
  { key: 'home', re: w('комнат', 'квартир', 'дом(?![а-яё]?ик)', 'спальн', 'кроват', 'диван', 'room', 'apartment', 'home', 'bed(?![a-z])', 'sofa', 'couch'), label: 'Apartment bedroom', short: 'the bedroom', environment: 'a small rented-apartment bedroom with an unmade bed, fairy lights and a window over the city', objects: ['unmade bed with a grey duvet', 'phone charging on the nightstand', 'fairy lights over the headboard', 'stack of books'], lighting: 'warm low lamplight and the cool blue glow of a phone screen', time: 'late night', weather: 'clear night outside the window', palette: 'warm tungsten, dusty pink, grey, phone-screen blue', enter: 'flops onto the bed still wearing {their} outfit', routine: 'scrolls {their} phone in the dark', trigger: 'switches off the lamp', obstacle: 'the bedroom door now opens onto the same bedroom', goal: 'finally get some sleep', frame: 'the bedroom window', artifactPlace: 'on the pillow', materials: 'cotton bedding, painted drywall, warm wood', textures: 'wrinkled sheets, soft knit blanket, dust in the lamplight', defaultWorld: 'space' },
  { key: 'bathroom', re: w('ванн', 'душ', 'зеркал', 'bathroom', 'shower', 'mirror'), label: 'Bathroom', short: 'the bathroom', environment: 'a compact bathroom with pale green tiles, a fogged mirror and a shower curtain', objects: ['fogged mirror', 'toothbrush in a glass', 'towel on a hook', 'rubber duck on the tub edge'], lighting: 'soft diffused overhead light, steam haze', time: 'morning', weather: 'not visible — steamy enclosed room', palette: 'mint green tile, white porcelain, chrome, yellow duck', enter: 'shuffles in and wipes the fog off the mirror', routine: 'brushes {their} teeth, half asleep', trigger: 'wipes the mirror clean', obstacle: 'the reflection stops copying {them}', goal: 'get ready for the day', frame: 'the bathroom mirror', artifactPlace: 'on the sink', materials: 'glazed tile, porcelain, chrome, vinyl curtain', textures: 'condensation drops, water streaks on glass, fluffy towel', defaultWorld: 'underwater' },
  { key: 'park', re: w('парк', 'лес', 'park', 'forest', 'woods'), label: 'City park', short: 'the park', environment: 'a quiet city park path lined with old linden trees and wooden benches', objects: ['wooden bench', 'old street lamp', 'fallen leaves on the path', 'a pigeon on the bench'], lighting: 'dappled afternoon sun through the leaves', time: 'afternoon', weather: 'mild autumn day, light breeze', palette: 'autumn orange, linden green, warm brown, soft sky blue', enter: 'walks down the path with {their} hands in {their} pockets', routine: 'sits on a bench and closes {their} eyes', trigger: 'opens {their} eyes', obstacle: 'every path leads back to the same bench', goal: 'clear {their} head on a walk', frame: 'the path ahead', artifactPlace: 'on the bench', materials: 'weathered wood, cast iron, gravel', textures: 'cracked bark, crunchy leaves, gravel grain', defaultWorld: 'enchanted' },
];

export const DEFAULT_LOCATION = LOCATIONS.find((l) => l.key === 'home')!;

export interface WorldPreset {
  key: string;
  re: RegExp;
  label: string;
  environment: string;
  objects: string[];
  lighting: string;
  time: string;
  weather: string;
  palette: string;
  creature: string;
  omens: [string, string, string];
  reveal: string;
  reaction: string;
  sound: string;
  artifact: string;
  materials: string;
  textures: string;
  atmosphere: string;
  ru: string;
  ruArtifact: string;
}

export const WORLDS: WorldPreset[] = [
  { key: 'dinosaurs', re: w('динозавр', 'юрск', 'ящер', 'dinosaur', 'jurassic', 't-?rex'), label: 'a prehistoric jungle with living dinosaurs', environment: 'a dense Cretaceous jungle of giant tree ferns, cycads and moss-covered boulders, steam rising from a shallow river', objects: ['an adult Tyrannosaurus rex', 'a herd of long-necked Brachiosaurus in the distance', 'giant dragonflies'], lighting: 'hazy golden-green sunlight filtering through a dense canopy, volumetric shafts through humid mist', time: 'late morning', weather: 'hot and humid, drifting mist', palette: 'deep fern green, wet moss, amber sunlight, mud brown', creature: 'a Tyrannosaurus rex', omens: ['the liquid in a nearby cup ripples in rhythmic rings', 'a deep thud shakes everything; small objects rattle', 'the light coming through {frame} turns a hazy green'], reveal: 'a Tyrannosaurus rex lowers its head until its amber eye fills {frame}', reaction: 'the dinosaur exhales; a puff of warm breath fogs the glass', sound: 'deep rhythmic footsteps, insect drone, a bird call that is not a bird', artifact: 'a torn, dripping-wet fern frond the size of a hand', materials: 'pebbled reptile skin, wet bark, moss', textures: 'rough scarred dinosaur skin, water dripping off fern fronds, steam', atmosphere: 'humid, primeval, dangerous yet awe-inspiring', ru: 'мир динозавров', ruArtifact: 'мокрый лист папоротника' },
  { key: 'space', re: w('космос', 'космич', 'планет', 'марс', 'луна', 'луне', 'невесом', 'space(?![a-z])', 'planet', 'mars(?![a-z])', 'moon', 'zero gravity', 'alien'), label: 'the surface of an alien planet', environment: 'a silent alien landscape of black volcanic rock under a violet sky with two moons and a ringed gas giant on the horizon', objects: ['a ringed gas giant', 'two small moons', 'floating dust particles'], lighting: 'hard white starlight with a violet rim from the gas giant, deep black shadows', time: 'endless alien dusk', weather: 'airless, perfectly still', palette: 'deep violet, obsidian black, icy white, a thin ring of orange', creature: 'a ringed gas giant', omens: ['loose hair and a receipt begin to float upward', 'all sound drops away into a pressurized hum', 'stars appear through {frame}'], reveal: 'the ringed planet rises through {frame} and fills it', reaction: 'a slow drift of weightless objects turns past {their} face', sound: 'sub-bass hum, total silence, a single heartbeat', artifact: 'a sprinkle of glittering grey moon dust', materials: 'basalt rock, fine regolith dust', textures: 'porous volcanic rock, sparkling dust, crisp star points', atmosphere: 'silent, vast, weightless', ru: 'другая планета', ruArtifact: 'горстка лунной пыли' },
  { key: 'underwater', re: w('под вод', 'подвод', 'океан', 'море', 'рыб', 'underwater', 'ocean', 'sea(?![a-z])', 'reef'), label: 'a coral reef deep underwater', environment: 'a sunlit coral reef ten meters underwater, schools of silver fish and swaying sea fans', objects: ['a whale shark', 'a school of silver sardines', 'swaying purple sea fans'], lighting: 'dancing caustic light patterns from the surface, blue-green ambient falloff', time: 'midday', weather: 'calm, clear water', palette: 'turquoise, deep ocean blue, coral pink, silver', creature: 'a whale shark', omens: ['a thin film of water spreads across the floor', 'tiny bubbles rise from nowhere', 'rippling caustic light slides across {their} face'], reveal: 'a whale shark glides slowly past {frame}', reaction: '{ref} exhales and a stream of bubbles rises from {their} lips', sound: 'muffled underwater ambience, whale song, bubbles', artifact: 'a small orange starfish in a puddle of seawater', materials: 'coral, sand, wet surfaces', textures: 'coral pores, suspended particles, rippling sand', atmosphere: 'weightless, calm, dreamlike', ru: 'коралловый риф под водой', ruArtifact: 'маленькая морская звезда' },
  { key: 'medieval', re: w('средневек', 'рыцар', 'medieval', 'knight', 'castle'), label: 'a medieval castle courtyard', environment: 'a muddy medieval castle courtyard with stone walls, banners and a blacksmith forge', objects: ['an armored knight on a black horse', 'red heraldic banners', 'a blacksmith forge with sparks'], lighting: 'smoky overcast daylight with warm orange forge glow', time: 'midday', weather: 'cold drizzle, smoke in the air', palette: 'stone grey, crimson banners, iron, firelight orange', creature: 'an armored knight on horseback', omens: ['a distant bell tolls, then hooves', 'the light flickers like candlelight', 'a waft of wood smoke curls through the air'], reveal: 'an armored knight on a black horse rides straight past {frame}', reaction: 'the knight stops and stares back, equally confused', sound: 'hooves on cobblestone, clanking armor, crowd murmur', artifact: 'a heavy iron horseshoe', materials: 'rough stone, chainmail, leather, wet wood', textures: 'mud splashes, rust on armor, frayed banners', atmosphere: 'gritty, loud, historical', ru: 'средневековый замок', ruArtifact: 'тяжёлая железная подкова' },
  { key: 'future', re: w('будущ', 'киберпанк', 'робот', 'future', 'cyberpunk', 'robot'), label: 'a neon megacity of the future', environment: 'a rain-soaked neon megacity of the future with holographic billboards and traffic lanes in the sky', objects: ['a flying car', 'holographic billboards', 'a delivery drone'], lighting: 'saturated magenta and cyan neon reflected in wet surfaces', time: 'night', weather: 'light rain, neon haze', palette: 'magenta, cyan, deep black, chrome', creature: 'a flying car', omens: ['electronics flicker and reboot showing unknown symbols', 'a hum of drones fills the air', 'neon light washes across {their} face'], reveal: 'a flying car drifts past {frame} under a giant hologram', reaction: 'a drone stops in front of {them} and scans {their} face', sound: 'synth drone, distant sirens, rain on metal', artifact: 'a glowing holographic ticket', materials: 'chrome, wet glass, carbon fiber', textures: 'rain streaks, neon reflections, holographic flicker', atmosphere: 'electric, dense, futuristic', ru: 'неоновый город будущего', ruArtifact: 'светящийся голографический билет' },
  { key: 'winter', re: w('зим', 'снег', 'снеж', 'мороз', 'лёд', 'льд', 'ледян', 'winter', 'snow', 'frozen', 'ice(?![a-z])'), label: 'a frozen arctic tundra', environment: 'an endless frozen tundra under the aurora borealis, wind-carved snow drifts and a lone polar bear', objects: ['a polar bear', 'green aurora ribbons', 'blowing snow'], lighting: 'cold blue moonlight with shifting green aurora light', time: 'polar night', weather: 'blizzard winds, -30°C', palette: 'ice blue, aurora green, snow white, navy', creature: 'a polar bear', omens: ['frost creeps across the glass in fern patterns', '{their} breath turns visible', 'snowflakes drift indoors'], reveal: 'a polar bear presses its nose to {frame}', reaction: 'frost spreads where the bear\'s breath touches the glass', sound: 'howling wind, creaking ice, muffled silence', artifact: 'a fresh pile of snow that refuses to melt', materials: 'packed snow, blue ice, thick fur', textures: 'ice crystals, wind-blown snow, frosted fur', atmosphere: 'freezing, silent, majestic', ru: 'ледяная тундра', ruArtifact: 'сугроб, который не тает' },
  { key: 'enchanted', re: w('сказ', 'волшеб', 'маги', 'фея', 'феи', 'дракон', 'fairy', 'magic', 'enchanted', 'dragon'), label: 'an enchanted fairy-tale forest', environment: 'an enchanted forest of giant glowing mushrooms, ancient twisted trees and floating lantern-like spores', objects: ['a small dragon', 'glowing mushrooms', 'floating golden spores'], lighting: 'soft bioluminescent turquoise glow with warm golden spore light', time: 'eternal twilight', weather: 'still air, floating spores', palette: 'turquoise glow, mossy green, gold, violet', creature: 'a small curious dragon', omens: ['tiny golden spores drift through the air', 'a houseplant uncurls and grows a flower', 'a soft chime rings from nowhere'], reveal: 'a small curious dragon lands and peers through {frame}', reaction: 'the dragon tilts its head and sneezes a puff of glitter', sound: 'wind chimes, soft magical shimmer, forest hum', artifact: 'a glowing golden feather', materials: 'velvet moss, bark, glowing fungus', textures: 'iridescent dragon scales, soft moss, spore glow', atmosphere: 'whimsical, magical, safe', ru: 'сказочный волшебный лес', ruArtifact: 'светящееся золотое перо' },
  { key: 'eighties', re: w('80-х', '80х', 'восьмидесят', '90-х', 'девяност', 'прошл', '1980', '1990', 'eighties', 'nineties', 'the past', 'retro'), label: 'the same place in 1986', environment: 'the same place but in 1986: wood panelling, CRT screens, cassette tapes and neon signage', objects: ['a boxy CRT television', 'a cassette Walkman', 'a neon sign'], lighting: 'warm tungsten mixed with pink neon, soft VHS bloom', time: '1986, evening', weather: 'warm summer evening', palette: 'teal, hot pink, mustard yellow, wood brown', creature: 'a 1980s crowd in big hair and windbreakers', omens: ['the phone screen turns into a pixelated green display', 'a synth-pop song fades in from nowhere', 'colors shift to warm VHS tones'], reveal: 'a crowd in 1980s windbreakers walks past {frame}', reaction: 'a stranger in a windbreaker points at {their} phone, baffled', sound: 'synth-pop, cassette hiss, VHS tracking noise', artifact: 'a mixtape cassette labeled with today\'s date', materials: 'vinyl, wood veneer, chrome, nylon', textures: 'VHS scan lines, film grain, glossy plastic', atmosphere: 'nostalgic, playful, surreal', ru: '1986 год', ruArtifact: 'кассета с сегодняшней датой' },
];

export const TWIST_RE = w('внезапн', 'вдруг', 'неожиданн', 'оказыва', 'превраща', 'попада', 'телепорт', 'перенос', 'просыпа', 'suddenly', 'turns into', 'finds (?:herself|himself|themselves|itself)', 'ends up', 'transported', 'teleport', 'wakes up', 'instead');
export const CONFLICT_RE = w('но ', 'не может', 'не мож', 'пыта', 'боит', 'опазд', 'застр', 'убега', 'погон', 'ссор', 'спор', 'меша', 'потер', 'ищет', 'сбежа', 'выбрат', 'but ', "can't", 'cannot', 'tries', 'trying', 'afraid', 'late(?![a-z])', 'stuck', 'chase', 'escape', 'lost', 'fight', 'argue', 'has to', 'must');
export const EMOTION_RE = w('плач', 'слез', 'смех', 'смеё', 'смеет', 'рад', 'счаст', 'страх', 'испуг', 'удивл', 'шок', 'зл', 'груст', 'любов', 'одинок', 'cry', 'tears', 'laugh', 'happy', 'joy', 'fear', 'scared', 'shock', 'surpris', 'angry', 'sad(?![a-z])', 'love', 'lonely');

export const TRIGGERS: { re: RegExp; text: string; ru: string }[] = [
  { re: w('открыва.{0,12}двер', 'opens? the door'), text: 'pushes the door open', ru: 'открывает дверь' },
  { re: w('двер', 'door'), text: 'pulls the door shut with a heavy thunk', ru: 'закрывает дверь' },
  { re: w('морга', 'моргн', 'blink'), text: 'blinks once, slowly', ru: 'моргает' },
  { re: w('чиха', 'чихн', 'sneez'), text: 'sneezes', ru: 'чихает' },
  { re: w('кнопк', 'нажима', 'button', 'press'), text: 'presses the button', ru: 'нажимает кнопку' },
  { re: w('засыпа', 'закрывает глаза', 'falls asleep', 'closes (?:her|his|its|their) eyes'), text: 'closes {their} eyes for a second', ru: 'закрывает глаза' },
];

export interface StylePreset {
  key: ReelStyle;
  cameraStyle: string;
  visualStyle: string;
  photorealism: string;
  lens: { wide: string; medium: string; close: string };
  sound: string;
  grade: string;
  move: string;
}

export const STYLE_PRESETS: Record<ReelStyle, StylePreset> = {
  cinematic: { key: 'cinematic', cameraStyle: 'cinema camera on dolly and crane: slow motivated moves, composed locked-off frames, 24 fps with a 180° shutter', visualStyle: 'feature-film realism with a teal-and-amber grade, subtle 35mm film grain and anamorphic oval bokeh', photorealism: 'photorealistic still, shot on ARRI Alexa 35 with anamorphic lenses, natural skin texture with visible pores, physically accurate light falloff', lens: { wide: '24mm anamorphic lens', medium: '40mm anamorphic lens', close: '75mm anamorphic lens' }, sound: 'low orchestral drone with designed impacts', grade: 'teal shadows, warm amber highlights', move: 'slow dolly' },
  ugc: { key: 'ugc', cameraStyle: 'handheld smartphone: slight natural shake, quick reframes, selfie-camera framing, 30 fps', visualStyle: 'authentic creator smartphone video with no color grade, phone HDR look, slightly clipped highlights', photorealism: 'photorealistic smartphone photo, iPhone 15 Pro main camera, unretouched skin, mild digital noise in the shadows', lens: { wide: '13mm ultra-wide phone lens', medium: '24mm phone main lens', close: '77mm phone telephoto lens' }, sound: 'raw on-phone audio, room tone, trending-style beat drop', grade: 'ungraded phone color', move: 'handheld push' },
  commercial: { key: 'commercial', cameraStyle: 'polished advertising coverage: motion-control precision, gimbal-smooth moves, crisp centered framing', visualStyle: 'premium commercial look, clean high-contrast lighting, saturated but controlled colors, glossy highlights', photorealism: 'photorealistic still, shot on RED V-Raptor, crisp micro-detail, clean skin, specular highlights on surfaces', lens: { wide: '18mm lens', medium: '35mm lens', close: '100mm macro lens' }, sound: 'punchy modern beat with crisp whooshes', grade: 'clean neutral blacks, vivid accent colors', move: 'gimbal glide' },
  comedy: { key: 'comedy', cameraStyle: 'punchy comedic coverage: snap zooms, whip pans, deadpan locked-off reaction shots held one beat too long', visualStyle: 'bright high-key comedic look, warm saturated colors, clean sitcom-style exposure', photorealism: 'photorealistic still, shot on Sony FX6, natural exaggerated-but-real expressions, soft even key light', lens: { wide: '20mm lens', medium: '35mm lens', close: '85mm lens' }, sound: 'comic timing beats, record scratch, deadpan silence', grade: 'warm, bright, saturated', move: 'snap zoom' },
  realistic: { key: 'realistic', cameraStyle: 'observational documentary camera: shoulder rig, available light, natural pacing, no stylized moves', visualStyle: 'naturalistic documentary realism, neutral color, true-to-life contrast, no stylization', photorealism: 'photorealistic still, shot on Sony FX3 with available light only, true skin tones, real-world imperfections', lens: { wide: '28mm lens', medium: '35mm lens', close: '85mm lens' }, sound: 'natural location sound, no score until the turn', grade: 'neutral, true-to-life', move: 'handheld drift' },
};

export const findWorld = (key: string) => WORLDS.find((x) => x.key === key) ?? WORLDS[0];
